import React, { useState } from "react";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Card } from "../components/Card";
import { Colors, Spacing } from "../theme";

const SECTIONS = [
  {
    title: "🏰 Getting Started",
    content: [
      "When you first join, you start with a small kingdom — some land, gold, food, and basic buildings.",
      "Your primary goal is to grow your networth (NW) by expanding land, training troops, constructing buildings, and researching technologies.",
      "Complete the Overview screen daily to collect your Daily Bonus and manage taxes.",
      "The game runs in real-time with hourly ticks — resources are generated and consumed continuously.",
    ],
  },
  {
    title: "💰 Economy",
    content: [
      "Resources: Gold, Food, Wood, Stone, Horses, Mana — each generated by specific buildings.",
      "Gold: Earned from peasant taxes. Higher tax rate = more gold but slower population growth.",
      "Food: Produced by farms. Troops and peasants consume food each hour.",
      "Wood & Stone: Produced by lumber mills and quarries. Required for building construction.",
      "Horses: Produced by stables. Required to train cavalry.",
      "Mana: Produced by temples (1 mana/hour per priest). Used for prayers.",
      "Population: Peasants grow over time depending on your tax rate and available land.",
      "Tip: Balance your tax rate — 10–20% is recommended for steady growth early on.",
    ],
  },
  {
    title: "🏗️ Buildings",
    content: [
      "Buildings are leveled structures that produce resources or provide other bonuses.",
      "Each building level costs gold and resources and takes time to complete.",
      "Farm → food production | Lumber Mill → wood | Quarry → stone | Stable → horses",
      "Barracks → train troops faster | Temple → mana + priests",
      "Library → research speed | Market → enables trading",
      "Keep → reduces troop upkeep | Watchtower → spy detection",
      "Only one building can be constructed at a time.",
    ],
  },
  {
    title: "⚔️ Combat",
    content: [
      "Attack other kingdoms to steal land and gold. Navigate to War Room → Attack.",
      "You can only attack kingdoms with a similar networth (within ~50% of yours).",
      "Troop types: Soldiers (balanced), Archers (ranged), Cavalry (fast), Pikemen (anti-cavalry), Elite Soldiers (powerful).",
      "Attacking costs troop health — expect casualties on both sides.",
      "Land taken is based on your victory margin and the defender's total land.",
      "If a kingdom has a Shield active, you cannot attack it.",
      "Explore: Gain land from unclaimed wilderness — safe but slower.",
      "Spy: Gather intel on enemy kingdoms without risking troops.",
    ],
  },
  {
    title: "🙏 Prayers & Mana",
    content: [
      "Build temples to generate priests and mana. Each temple level = 5 priests.",
      "Priests convert mana into income: 1 mana per priest per hour.",
      "Prayers cost mana upfront and provide bonuses for a set duration.",
      "Available prayers: Harvest (food), Prosperity (gold), Growth (population), Fortify (stone/wood), War Blessing (horse+troop).",
      "Multiple prayers can be active simultaneously.",
      "Navigate to Holy Circle (Market tab) to manage prayers.",
    ],
  },
  {
    title: "🤝 Alliances",
    content: [
      "Create or join an alliance to cooperate with other players.",
      "Alliance members can contribute resources to alliance projects.",
      "Set diplomatic relations with other alliances: Neutral, Friendly, Allied, War.",
      "Allied kingdoms can coordinate attacks and share intel.",
      "Alliance forums allow secure messaging between members.",
      "Each kingdom can only be in one alliance at a time.",
    ],
  },
  {
    title: "🛒 Marketplace",
    content: [
      "List resources for sale (gold, food, wood, stone, horses).",
      "Resources are deducted immediately when you create a listing.",
      "Buyers pay gold; sellers receive 95% of the sale price (5% marketplace tax).",
      "Cancel your own listings to refund the remaining unsold quantity.",
      "Check Market History to track your trades and active listings.",
      "Requires a Market building to be constructed in your kingdom.",
    ],
  },
  {
    title: "🏘️ Settlements & Research",
    content: [
      "Settlements: Found new towns to unlock additional building slots and bonuses.",
      "Each settlement type specializes: Military, Economic, Research, Agricultural, Trade, or Arcane.",
      "Settlements have their own buildings that can be upgraded independently.",
      "Research: Unlock permanent upgrades through the tech tree.",
      "Tech categories include Economy, Military, Diplomacy, and Arcane.",
      "Researching a technology takes time and gold — some techs have prerequisites.",
      "Higher-level techs provide compounding bonuses — prioritize your playstyle.",
    ],
  },
];

export function HowToPlayScreen() {
  const [expanded, setExpanded] = useState<number | null>(0);

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.pageTitle}>How to Play</Text>
        <Text style={styles.pageSubtitle}>Crownforge Kingdom Guide</Text>

        {SECTIONS.map((section, i) => (
          <Card key={i} style={{ marginBottom: 0 }}>
            <TouchableOpacity
              onPress={() => setExpanded(expanded === i ? null : i)}
              style={styles.sectionHeader}
              activeOpacity={0.7}
            >
              <Text style={styles.sectionTitle}>{section.title}</Text>
              <Text style={styles.chevron}>{expanded === i ? "▲" : "▼"}</Text>
            </TouchableOpacity>

            {expanded === i && (
              <View style={styles.sectionBody}>
                {section.content.map((line, j) => (
                  <View key={j} style={styles.bulletRow}>
                    <Text style={styles.bullet}>•</Text>
                    <Text style={styles.bulletText}>{line}</Text>
                  </View>
                ))}
              </View>
            )}
          </Card>
        ))}

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Good luck, and may your kingdom prosper! 👑
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  content: { padding: Spacing.md, gap: Spacing.sm },
  pageTitle: { fontSize: 26, fontWeight: "900", color: Colors.accent, textAlign: "center", marginBottom: 4 },
  pageSubtitle: { fontSize: 13, color: Colors.textMuted, textAlign: "center", marginBottom: 8, letterSpacing: 0.5 },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionTitle: { fontSize: 15, fontWeight: "800", color: Colors.textMain, flex: 1 },
  chevron: { color: Colors.textMuted, fontSize: 12 },
  sectionBody: { marginTop: 12, gap: 8 },
  bulletRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  bullet: { color: Colors.accent, fontSize: 14, lineHeight: 20 },
  bulletText: { flex: 1, fontSize: 13, color: Colors.textMuted, lineHeight: 20 },
  footer: { paddingVertical: 16, alignItems: "center" },
  footerText: { fontSize: 14, color: Colors.textMuted, fontStyle: "italic" },
});
